name: Flutter Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Instalar dependências
        run: |
          cd frontend_flutter
          flutter pub get

      - name: Build APK
        run: |
          cd frontend_flutter
          flutter build apk --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: frontend_flutter/build/app/outputs/flutter-apk/app-release.apk
