name: frontend_flutter
description: Flutter app integrado com Laravel e Firebase
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
